#!/bin/bash

set -euo pipefail

observation=${1:-}
expected_revision=${2:-}

fail() { echo "verify-omarchy-notification-observation: $*" >&2; exit 1; }

[[ -f $observation && ! -L $observation ]] || fail "observation is missing or unsafe"
[[ $expected_revision =~ ^[0-9a-f]{40}$ ]] || fail "expected revision must be a full Git commit"

ruby -rjson -rtime -e '
  value = JSON.parse(File.read(ARGV.fetch(0)))
  abort "wrong notification schema" unless value["schemaVersion"] == 1
  abort "wrong source revision" unless value["sourceRevision"] == ARGV.fetch(1)
  abort "macOS did not accept the notification request" unless value["macOSRequestAccepted"] == true
  abort "Guest boot ID is missing" unless value["guestBootID"].is_a?(String) && !value["guestBootID"].empty?
  abort "Guest notification ID is missing" unless value["guestNotificationID"].is_a?(String) && !value["guestNotificationID"].empty?
  title = value["notificationTitle"]
  abort "notification was not generated by the acceptance probe" unless
    title.is_a?(String) && title.match?(/\AEZVM notification [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/)
  observed = Time.iso8601(value.fetch("observedAt"))
  age = Time.now.utc - observed
  abort "notification observation is in the future" if age < -300
  abort "notification observation is older than 24 hours" if age > 86_400
' "$observation" "$expected_revision"

echo "Verified EZVM Omarchy Guest-to-macOS notification observation."
